version: '3'
services:
  postgres:
    image: mdillon/postgis
    container_name: pg-docker
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=postgres
    expose:
      - 5432  
    ports:
      - 5432:5432
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/z_init.sql
      - ./postgres/data:/var/lib/postgresql/data
 
  weather-app:
    build: ./weather-api
    container_name: weather-app-docker 
    environment:
      - POSTGRES_HOST=postgres
      - MAPQUEST_API_KEY=${MAPQUEST_API_KEY}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    expose:
      - 8080
    ports:
      - 8080:8080
    depends_on:
      - postgres
    links:
      - "postgres:pg-docker"
  
  weather-data-loader:
    build: ./weather-data-loader    
    container_name: weather-data-loader-docker 
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}   
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-dev}
    depends_on:
      - postgres
    links:
      - "postgres:pg-docker"  
        
