version: '3'
services:
  postgres:
    image: mdillon/postgis
    container_name: pg-docker
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    expose:
      - 5432  
    ports:
      - 5432:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    restart: always
 
  weather-app:
    image: weather-app:latest
    container_name: weather-app-docker 
    expose:
      - 8080
    ports:
      - 8080:8080
    depends_on:
      - postgres
    links:
      - "postgres:pg-docker"
        
