version: '3'
services:
  postgres:
    image: mdillon/postgis
    container_name: pg-docker
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=postgres
    expose:
      - 5432  
    ports:
      - 5432:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
 
  weather-app:
    image: weather-app:latest
    container_name: weather-app-docker 
    environment:
      - POSTGRES_HOST=postgres
      - MAPQUEST_API_KEY=${MAPQUEST_API_KEY}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    expose:
      - 8080
    ports:
      - 8080:8080
    depends_on:
      - postgres
    links:
      - "postgres:pg-docker"
        
