postgres:
  image: mdillon/postgis
  container_name: pg-docker
  environment:
    MYSQL_DATABASE: dataflow
    MYSQL_USER: root
    POSTGRES_PASSWORD: docker
  ports:
      - "5432:5432"
  volumes:
    - ./postgres/data:/var/lib/postgresql/data
    - ./postgres/init.sql:/docker-entrypoint-initdb.d/z_init.sql
